### ISSUE TITLE
Recursion error inspecting DotMap with inspect.unwrap

### ISSUE THREAD

**Issue by calebmarchent** [drgrib/dotmap#63]
If I try to unwrap an object to class DotMap I get recursion error; we saw this trying to Document our code using Sphinx 3.0.3. Initially, I raised it on Sphinx; but with the feedback I got; it looks like a DotMap issue?

https://github.com/sphinx-doc/sphinx/issues/7764

**To reproduce:**
```python
# dotmap_exporter.py
from dotmap import DotMap

testdotmap = DotMap()
```
and then use this module in python like so
```python
Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import inspect
>>> import sys
>>> import dotmap_exporter
>>> sys.setrecursionlimit(50)
>>> inspect.unwrap(dotmap_exporter.testdotmap)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/calebm/.conda/envs/py36/lib/python3.6/inspect.py", line 516, in unwrap
    raise ValueError('wrapper loop when unwrapping {!r}'.format(f))
  File "/home/calebm/upstream/dotmap/dotmap/__init__.py", line 125, in __repr__
    return str(self)
  File "/home/calebm/upstream/dotmap/dotmap/__init__.py", line 119, in __str__
    items.append('{0}={1}'.format(k, repr(v)))
  File "/home/calebm/upstream/dotmap/dotmap/__init__.py", line 125, in __repr__
    return str(self)
  File "/home/calebm/upstream/dotmap/dotmap/__init__.py", line 119, in __str__
    items.append('{0}={1}'.format(k, repr(v)))
  File "/home/calebm/upstream/dotmap/dotmap/__init__.py", line 125, in __repr__
    return str(self)
  File "/home/calebm/upstream/dotmap/dotmap/__init__.py", line 119, in __str__
    items.append('{0}={1}'.format(k, repr(v)))
  File "/home/calebm/upstream/dotmap/dotmap/__init__.py", line 125, in __repr__
    return str(self)
  File "/home/calebm/upstream/dotmap/dotmap/__init__.py", line 119, in __str__
    items.append('{0}={1}'.format(k, repr(v)))
  File "/home/calebm/upstream/dotmap/dotmap/__init__.py", line 125, in __repr__
    return str(self)
  File "/home/calebm/upstream/dotmap/dotmap/__init__.py", line 119, in __str__
    items.append('{0}={1}'.format(k, repr(v)))
RecursionError: maximum recursion depth exceeded
```

**Comment by calebmarchent** [comment]
My assessment of the bug is that: Unwrap tries to query the `__wrapped__` property of the DotMap class. As there is no implementation of `__wrapped__`; it follows down through the `__getattr__`, to `__getitem__` and then because not known it calls `__setitem__` to point __wrapped__ at the class. As unwrap is trying to walk recursively through the stack it then does the same thing again with the returned instance of the class.

I took a look at cpython to see how other classes handle this scenario and found that Enum and other classes explicitly exclude dunder properties, raising AttributeError. I propose that to solve this we follow the same pattern?

Please can you review my findings, confirm if I am going in the right direction here - before I proceed further with this investigation?

**Comment by drgrib** [comment]
Hey @calebmarchent. I appreciate your time and attention to this issue. I don't actively develop in Python anymore so I no longer write code for this repo. However, I still review, approve, and merge PRs if you would like to continue to investigate and write a solution.

**Comment by drgrib** [comment]
I see you beat me to the punch on this :) Thanks for the contribution.
