### ISSUE TITLE
Additional "size" key being added to DotMap when converting from a nested dictionary

### ISSUE THREAD

**Issue by philip928lin** [drgrib/dotmap#97]
When I convert a nested dictionary, it appears that additional items are added to the DotMap with the keys named "size" or "compute." 
This sometimes causes the problem when doing "for k, v in DotMapObject.items():"
Those additional items will also stay when converting back to the dictionary.
Does anyone know why? and how to avoid that?

![image](https://github.com/drgrib/dotmap/assets/23210992/f20ff89d-b365-468c-b259-d609f1f7e100)

**Comment by FelixSchwarz** [comment]
Can you provide us with a code snippet that demonstrates the problem?

**Comment by templiert** [comment]
I think that OP made unwanted autovivifications by calling d.size or d.compute
```python
from dotmap import DotMap

d = DotMap()
print(f"{"a" in d=}")
d.a
print(f"{"a" in d=}")
```
Output:
```
"a" in d=False
"a" in d=True
```
Use `_dynamic=False`

```python
d = DotMap(_dynamic=False)
print(f"{"a" in d=}")
d.a
```
Output:
```
"a" in d=False
Traceback (most recent call last):
  File "C:\software\repos\myrepo\tests\dotmap_autovivification.py", line 10, in <module>
    d.a
  File "C:\software\miniforge\envs\myenv\Lib\site-packages\dotmap\__init__.py", line 125, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{k}'") from None
AttributeError: 'DotMap' object has no attribute 'a'
```
